/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-08 02:48:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import member.model.dto.Member;
import java.util.ArrayList;
import member.model.dto.MemberRole;
import member.model.dto.Member;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1654650331275L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1652334477701L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.dto.Member");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("member.model.dto.MemberRole");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	// System.out.println("loginMember@header.jsp = " + loginMember);
	
	String msg = (String) session.getAttribute("msg");
	if(msg != null)
		session.removeAttribute("msg");
	
	String saveId = null; // 아이디저장을 체크한 경우, memberId값이 담길 변수
	Cookie[] cookies = request.getCookies();
	if(cookies != null){
		for(Cookie cookie : cookies){
			// System.out.println("Cookie{" + cookie.getName() + "=" + cookie.getValue() + "}");
			if("saveId".equals(cookie.getName())){
				saveId = cookie.getValue();
			}
		}
	}
	else {
		// System.out.println("> 이번 요청에 전달된 cookie가 없습니다.");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hello MVC</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("window.onload = () => {\r\n");
 if(msg != null){ 
      out.write("\r\n");
      out.write("	alert(\"");
      out.print( msg );
      out.write("\");\r\n");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("	document.loginFrm.onsubmit = (e) => {\r\n");
      out.write("		const memberIdVal = memberId.value;\r\n");
      out.write("		const passwordVal = password.value;\r\n");
      out.write("		\r\n");
      out.write("		if(!/^.{4,}$/.test(memberIdVal)){\r\n");
      out.write("			alert(\"유효한 아이디를 입력해주세요.\");\r\n");
      out.write("			memberId.select();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(!/^.{4,}$/.test(passwordVal)){\r\n");
      out.write("			alert(\"유효한 비밀번호를 입력해주세요.\");\r\n");
      out.write("			password.select();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	};	\r\n");
 } 
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<h1>Hello MVC</h1>\r\n");
      out.write("			<div class=\"login-container\">\r\n");
      out.write("			");
 if(loginMember == null){ 
      out.write("\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<!-- 로그인폼 시작 -->\r\n");
      out.write("				<form id=\"loginFrm\" name=\"loginFrm\" method=\"POST\" action=\"");
      out.print( request.getContextPath() );
      out.write("/member/login\">\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"text\" name=\"memberId\" id=\"memberId\" placeholder=\"아이디\" tabindex=\"1\" value=\"");
      out.print( saveId != null ? saveId : "" );
      out.write("\"></td>\r\n");
      out.write("							<td><input type=\"submit\" value=\"로그인\" tabindex=\"3\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"password\" name=\"password\" id=\"password\" placeholder=\"비밀번호\" tabindex=\"2\"></td>\r\n");
      out.write("							<td></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"2\">\r\n");
      out.write("								<input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print( saveId != null ? "checked" : "" );
      out.write("/>\r\n");
      out.write("								<label for=\"saveId\">아이디저장</label>&nbsp;&nbsp;\r\n");
      out.write("								<input type=\"button\" value=\"회원가입\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/memberEnroll';\">\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</form>\r\n");
      out.write("				<!-- 로그인폼 끝-->\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<table id=\"login\">\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print( loginMember.getMemberName() );
      out.write("님, 안녕하세요.</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<input type=\"button\" value=\"내정보보기\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/memberView';\"/>\r\n");
      out.write("								<input type=\"button\" value=\"로그아웃\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/logout';\"/>							\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 메인메뉴 시작 -->\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul class=\"main-nav\">\r\n");
      out.write("					<li class=\"home\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\">Home</a></li>\r\n");
      out.write("					<li class=\"notice\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("					<li class=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/board/boardList\">게시판</a></li>\r\n");
      out.write("					<li class=\"photo\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/photo/photoList\">사진게시판</a></li>\r\n");
      out.write("					<li class=\"chat\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/chat/chatroom\">채팅</a></li>\r\n");
      out.write("					");
 if(loginMember != null && loginMember.getMemberRole() == MemberRole.A) { 
      out.write("\r\n");
      out.write("						<li class=\"admin\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\">회원관리</a></li>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<!-- 메인메뉴 끝-->\r\n");
      out.write("					\r\n");
      out.write("		</header>\r\n");
      out.write("			\r\n");
      out.write("		<section id=\"content\">");
      out.write('\r');
      out.write('\n');

	List<Member> list = (List<Member>) request.getAttribute("list");
	String pagebar = (String) request.getAttribute("pagebar");
	
	String searchType = request.getParameter("searchType");
	String searchKeyword = request.getParameter("searchKeyword");


      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/admin.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div#search-container {width: 100%; margin:0 0 10px 0; padding:3px; background-color: rgba(0, 188, 212, 0.3);}\r\n");
      out.write("div#search-memberId {display: ");
      out.print( "member_id".equals(searchType) || searchType == null ? "inline-block" : "none" );
      out.write(";}\r\n");
      out.write("div#search-memberName {display: ");
      out.print( "member_name".equals(searchType) ? "inline-block" : "none" );
      out.write(";}\r\n");
      out.write("div#search-gender {display: ");
      out.print( "gender".equals(searchType) ? "inline-block" : "none" );
      out.write(";}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<section id=\"memberList-container\">\r\n");
      out.write("	<h2>회원관리</h2>	\r\n");
      out.write("	<div id=\"search-container\">\r\n");
      out.write("    	<label for=\"searchType\">검색타입 :</label> \r\n");
      out.write("        <select id=\"searchType\">\r\n");
      out.write("            <option value=\"member_id\" ");
      out.print("member_id".equals(searchType)?"selected":"");
      out.write(">아이디</option>		\r\n");
      out.write("			<option value=\"member_name\" ");
      out.print("member_name".equals(searchType)?"selected":"");
      out.write(">회원명</option>\r\n");
      out.write("			<option value=\"gender\" ");
      out.print("gender".equals(searchType)?"selected":"");
      out.write(">성별</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <div id=\"search-memberId\" class=\"search-type\">\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberFinder\">\r\n");
      out.write("                <input type=\"hidden\" name=\"searchType\" value=\"member_id\"/>\r\n");
      out.write("                <input type=\"text\" name=\"searchKeyword\"  size=\"25\" placeholder=\"검색할 아이디를 입력하세요.\" value=\"");
      out.print( "member_id".equals(searchType) ? searchKeyword : "" );
      out.write("\"/>\r\n");
      out.write("                <button type=\"submit\">검색</button>			\r\n");
      out.write("            </form>	\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"search-memberName\" class=\"search-type\">\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberFinder\">\r\n");
      out.write("                <input type=\"hidden\" name=\"searchType\" value=\"member_name\"/>\r\n");
      out.write("                <input type=\"text\" name=\"searchKeyword\" size=\"25\" placeholder=\"검색할 이름을 입력하세요.\" value=\"");
      out.print( "member_name".equals(searchType) ? searchKeyword : "" );
      out.write("\"/>\r\n");
      out.write("                <button type=\"submit\">검색</button>			\r\n");
      out.write("            </form>	\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"search-gender\" class=\"search-type\">\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberFinder\">\r\n");
      out.write("                <input type=\"hidden\" name=\"searchType\" value=\"gender\"/>\r\n");
      out.write("                <input type=\"radio\" name=\"searchKeyword\" value=\"M\" ");
      out.print("gender".equals(searchType) && "M".equals(searchKeyword)?"checked":"");
      out.write("> 남\r\n");
      out.write("                <input type=\"radio\" name=\"searchKeyword\" value=\"F\" ");
      out.print("gender".equals(searchType) && "F".equals(searchKeyword)?"checked":"");
      out.write("> 여\r\n");
      out.write("                <button type=\"submit\">검색</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	\r\n");
      out.write("	<table id=\"tbl-member\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>아이디</th>\r\n");
      out.write("				<th>이름</th>\r\n");
      out.write("				<th>회원권한</th>\r\n");
      out.write("				<th>성별</th>\r\n");
      out.write("				<th>생년월일</th>\r\n");
      out.write("				<th>이메일</th>\r\n");
      out.write("				<th>전화번호</th>\r\n");
      out.write("				<th>주소</th>\r\n");
      out.write("				<th>취미</th>\r\n");
      out.write("				<th>가입일</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");

		if(list != null && !list.isEmpty()){
			for(Member member : list){

      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print( member.getMemberId() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( member.getMemberName() );
      out.write("</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<select class=\"member-role\" data-member-id=\"");
      out.print( member.getMemberId() );
      out.write("\">\r\n");
      out.write("						<option value=\"");
      out.print( MemberRole.A );
      out.write('"');
      out.write(' ');
      out.print( member.getMemberRole() == MemberRole.A ? "selected" : "" );
      out.write(">관리자</option>\r\n");
      out.write("						<option value=\"");
      out.print( MemberRole.U );
      out.write('"');
      out.write(' ');
      out.print( member.getMemberRole() == MemberRole.U ? "selected" : "" );
      out.write(">일반회원</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>");
      out.print( member.getGender() != null ? member.getGender() : "" );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( member.getBirthday() != null ? member.getBirthday() : "" );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( member.getEmail() != null ? member.getEmail() : "" );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( member.getPhone() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( member.getAddress() != null ? member.getAddress() : "" );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( member.getHobby() != null ? member.getHobby() : "" );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( member.getEnrollDate() );
      out.write("</td>\r\n");
      out.write("			</tr>			\r\n");

			}
		}
		else {

      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"10\">조회된 회원이 없습니다.</td>\r\n");
      out.write("			</tr>\r\n");

		}

      out.write("		\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("	<div id=\"pagebar\">\r\n");
      out.write("		");
      out.print( pagebar );
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<form \r\n");
      out.write("	action=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberRoleUpdate\" \r\n");
      out.write("	name=\"updateMemberRoleFrm\"\r\n");
      out.write("	method=\"POST\">\r\n");
      out.write("	<input type=\"hidden\" name=\"memberId\" />\r\n");
      out.write("	<input type=\"hidden\" name=\"memberRole\" />\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("searchType.addEventListener('change', (e) => {\r\n");
      out.write("	const {value} = e.target; // 구조분해할당\r\n");
      out.write("	console.log(value);\r\n");
      out.write("	\r\n");
      out.write("	document.querySelectorAll(\".search-type\").forEach((div) => {\r\n");
      out.write("		div.style.display = \"none\";\r\n");
      out.write("	});\r\n");
      out.write("	let id = \"\";\r\n");
      out.write("	switch(value){\r\n");
      out.write("		case \"member_id\": id = \"search-memberId\"; break; \r\n");
      out.write("		case \"member_name\": id = \"search-memberName\"; break; \r\n");
      out.write("		case \"gender\": id = \"search-gender\"; break; \r\n");
      out.write("	}\r\n");
      out.write("	document.querySelector(`#${id}`).style.display = \"inline-block\";\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.querySelectorAll(\".member-role\").forEach((select) => {\r\n");
      out.write("	select.addEventListener('change', (e) => {\r\n");
      out.write("		// console.dir(e.target);\r\n");
      out.write("		// console.log(e.target.dataset.memberId); // key값을 조회시에는 camelcasing으로 참조 \r\n");
      out.write("		// console.log(e.target.value); // \"U\" \"A\"\r\n");
      out.write("		const memberId = e.target.dataset.memberId;\r\n");
      out.write("		const memberRole = e.target.value;\r\n");
      out.write("		\r\n");
      out.write("		// jsp에서 js의 Template String문법 사용시 반드시 escaping처리할 것\r\n");
      out.write("		// (jsp의 EL문법과 충돌)\r\n");
      out.write("		if(confirm(`[${memberId}]의 권한을 [${memberRole}]로 변경하시겠습니까?`)){\r\n");
      out.write("			const frm = document.updateMemberRoleFrm;\r\n");
      out.write("			frm.memberId.value = memberId;\r\n");
      out.write("			frm.memberRole.value = memberRole;\r\n");
      out.write("			frm.submit();\r\n");
      out.write("		}\r\n");
      out.write("		else {\r\n");
      out.write("			e.target.querySelector(\"[selected]\").selected = true;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<footer>\r\n");
      out.write("			<p>&lt;Copyright 1998-2021 <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
